export const VISIBLE_MODAL_UPLOAD = 'VISIBLE_MODAL_UPLOAD'
export const CLEAR_STATE_UPLOAD = 'CLEAR_STATE_UPLOAD'
export const SET_DATA_UPLOAD = 'SET_DATA_UPLOAD'

export const POST_PRODUCT = 'POST_PRODUCT'
export const PATCH_PRODUCT = 'PATCH_PRODUCT'
